version: "3"
services:
    pgr_gw_core:
        build:
            context: ./components/gw_core
        command: npm start
        ports:
            - "3006:3006"
        depends_on:
            - pgr_adapter_proxy
            - pgr_node_manager
            - pgr_node_proxy
            - pgr_user_manager
            - redis
        environment:
            - NODE_ENV=dev
            - mgmt_api_key=nodemanager&*()
        networks:
            - pgr-net
        links:
            - pgr_adapter_proxy
            - pgr_node_manager
            - pgr_node_proxy
            - pgr_user_manager
            - redis

    pgr_adapter_proxy:
        build:
            context: ./components/adapter_proxy
        command: npm start
        depends_on:
            - redis
        environment:
            - NODE_ENV=dev
        networks:
            - pgr-net
        links:
            - redis

    pgr_node_proxy:
        build:
            context: ./components/json_rpc_proxy
        command: npm start
        depends_on:
            - redis
        environment:
            - NODE_ENV=dev
        networks:
            - pgr-net
        links:
            - redis

    pgr_node_manager:
        build:
            context: ./components/node_manager
        command: npm start
        depends_on:
            - redis
            - mongo
        environment:
            - NODE_ENV=dev
            - dbname=pgw_dev
            - dbuser=pgwUser
            - dbpass=pgwPass
            - dburi=mongo:27017
        networks:
            - pgr-net
        links:
            - redis
            - mongo

    pgr_user_manager:
        build:
            context: ./components/user_services
        command: npm start
        depends_on:
            - redis
            - mongo
        environment:
            - NODE_ENV=dev
            - dbname=pgw_dev
            - dbuser=pgwUser
            - dbpass=pgwPass
            - dburi=mongo:27017
        networks:
            - pgr-net
        links:
            - redis
            - mongo


    mongo:
        image: mongo:latest
        container_name: pgw_mongo
        restart: always
        volumes:
            - db-data:/data/db
        networks:
            - pgr-net
        ports:
            - "27017:27017"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: toor

    mongo-express:
        image: mongo-express
        depends_on:
            - mongo
        networks:
            - pgr-net
        restart: always
        ports:
            - "8081:8081"
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: toor

    redis:
        image: redis:latest
        networks:
            - pgr-net
        restart: always
        ports:
            - "6379:6379"

networks:
    ? pgr-net

volumes:
    ? db-data
