version: '3'
services:

  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - db-data:/data/db
    networks:
        - pgw-net
    ports:
        - "27017:27017"
    environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: toor

  mongo-express:
    image: mongo-express
    depends_on:
        - mongo
    networks:
        - pgw-net
    restart: always
    ports:
        - "8081:8081"
    environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: toor


networks:
    pgw-net:

volumes:
    db-data:
